# To execute this docker-compose yml file use `docker-compose -f docker-compose-with-jenkins-selenium-grid.yml up --build`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker-compose -f docker-compose-with-jenkins-selenium-grid.yml down`
version: "3"
networks: 
  component_test: 
    ipam:
     config: 
      - subnet: 172.20.0.0/24

services:
  jenkins:
    user: root
    build: .
    ports:
      - "5000:5000"
    image: "jenkins-in-docker"
    ports:
      - "8095:8080"
      - "4444:4444"
      - "50000:50000"
    networks:
       component_test:
         ipv4_address: 172.20.0.6
    depends_on:
      - selenium-router
    volumes:
      - ./jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      
  selenium-event-bus:
    image: selenium/event-bus:4.0.0-rc-1-prerelease-20210823
    container_name: selenium-event-bus
    ports:
      - "4442:4442"
      - "4443:4443"
      - "5557:5557"
    networks:
       component_test:
         ipv4_address: 172.20.0.7
    
  selenium-sessions:
    image: selenium/sessions:4.0.0-rc-1-prerelease-20210823
    container_name: selenium-sessions
    ports:
      - "5556:5556"
    depends_on:
      - selenium-event-bus
    environment:
      - SE_EVENT_BUS_HOST=selenium-event-bus
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
       component_test:
         ipv4_address: 172.20.0.8

  selenium-session-queue:
    image: selenium/session-queue:4.0.0-rc-1-prerelease-20210823
    container_name: selenium-session-queue
    ports:
      - "5559:5559"
    depends_on:
      - selenium-event-bus
    environment:
      - SE_EVENT_BUS_HOST=selenium-event-bus
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    networks:
       component_test:
         ipv4_address: 172.20.0.9

  selenium-distributor:
    image: selenium/distributor:4.0.0-rc-1-prerelease-20210823
    container_name: selenium-distributor
    ports:
      - "5553:5553"
    depends_on:
      - selenium-event-bus
      - selenium-sessions
      - selenium-session-queue
    environment:
      - SE_EVENT_BUS_HOST=selenium-event-bus
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_SESSIONS_MAP_HOST=selenium-sessions
      - SE_SESSIONS_MAP_PORT=5556
      - SE_SESSION_QUEUE_HOST=selenium-session-queue
      - SE_SESSION_QUEUE_PORT=5559
    networks:
       component_test:
         ipv4_address: 172.20.0.10

  selenium-router:
    image: selenium/router:4.0.0-rc-1-prerelease-20210823
    container_name: selenium-router
    networks:
       component_test:
         ipv4_address: 172.20.0.11
    hostname: grid
    domainname: grid.com
    ports:
      - "4445:4444"
    depends_on:
      - selenium-distributor
      - selenium-sessions
      - selenium-session-queue
    environment:
      - SE_DISTRIBUTOR_HOST=selenium-distributor
      - SE_DISTRIBUTOR_PORT=5553
      - SE_SESSIONS_MAP_HOST=selenium-sessions
      - SE_SESSIONS_MAP_PORT=5556
      - SE_SESSION_QUEUE_HOST=selenium-session-queue
      - SE_SESSION_QUEUE_PORT=5559

  chrome:
    image: selenium/node-chrome:4.0.0-rc-1-prerelease-20210823
    shm_size: 2gb
    depends_on:
      - selenium-event-bus
    environment:
      - SE_EVENT_BUS_HOST=selenium-event-bus
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=2
    ports:
      - "6900:5900"
    networks:
       component_test:
         ipv4_address: 172.20.0.12

  edge:
    image: selenium/node-edge:4.0.0-rc-1-prerelease-20210823
    shm_size: 2gb
    depends_on:
      - selenium-event-bus
    environment:
      - SE_EVENT_BUS_HOST=selenium-event-bus
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=2
    ports:
      - "6901:5900"
    networks:
       component_test:
         ipv4_address: 172.20.0.13

  firefox:
    image: selenium/node-firefox:4.0.0-rc-1-prerelease-20210823
    shm_size: 2gb
    depends_on:
      - selenium-event-bus
    environment:
      - SE_EVENT_BUS_HOST=selenium-event-bus
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=2
    ports:
      - "6902:5900"
    networks:
       component_test:
         ipv4_address: 172.20.0.14

